import { Inter } from 'next/font/google'
import './globals.css'
import Logobar from './Components/Logobar'
import Navbar from './Components/Navbar'
import Tv from './Components/Tv'
import Framer from './Components/Framer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kreator ||Chinese Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Navbar />
         {/* <Logobar /> */}
        {children}
        
        </body>
    </html>
  )
}
